import { DocArticle } from "@/components/docsChrome";

const html = '<p>These pages are for developers and maintainers. Day-to-day clinic users can ignore this section.</p>\n<h2>Stack</h2>\n<table>\n<thead><tr><th>Layer</th><th>Technology</th></tr></thead>\n<tbody>\n<tr><td>App</td><td>Next.js (App Router) + TypeScript + React + ShadCN UI</td></tr>\n<tr><td>Link &amp; settings storage</td><td>Upstash Redis</td></tr>\n<tr><td>File destination</td><td>Microsoft Graph / OneDrive</td></tr>\n<tr><td>Auth</td><td>Microsoft Entra ID (MSAL) with PKCE; signed HttpOnly cookies</td></tr>\n<tr><td>Email</td><td>Azure Communication Services</td></tr>\n<tr><td>Optional on Vercel</td><td>Vercel Blob for durable OneDrive token cache</td></tr>\n</tbody></table>\n<h2>Surfaces</h2>\n<table>\n<thead><tr><th>Surface</th><th>URL</th><th>Users</th></tr></thead>\n<tbody>\n<tr><td>Public landing</td><td><code>/</code></td><td>Anyone</td></tr>\n<tr><td>Parent upload</td><td><code>/link</code> via <code>/link/{token}</code></td><td>Parents / caregivers with a valid invitation</td></tr>\n<tr><td>Admin console</td><td><code>/console</code></td><td>Allowlisted Microsoft accounts</td></tr>\n<tr><td>Admin docs</td><td><code>/docs</code></td><td>Allowlisted Microsoft accounts</td></tr>\n<tr><td>Public info</td><td><code>/info</code>, <code>/privacy</code>, <code>/tos</code></td><td>Anyone</td></tr>\n</tbody></table>\n<h2>Key modules in the application repo</h2>\n<table>\n<thead><tr><th>Path</th><th>Responsibility</th></tr></thead>\n<tbody>\n<tr><td><code>lib/server.ts</code></td><td>Redis, config, links, MSAL/token cache, cookies, Graph helpers</td></tr>\n<tr><td><code>lib/upload.ts</code></td><td>Browser upload orchestration</td></tr>\n<tr><td><code>lib/email.ts</code></td><td>ACS send helper</td></tr>\n<tr><td><code>lib/appConfig.ts</code></td><td>Shared types and defaults</td></tr>\n<tr><td><code>lib/uploadFilename.ts</code> / <code>lib/age.ts</code></td><td>Naming and age math</td></tr>\n<tr><td><code>components/uploadArea.tsx</code></td><td>File picker / upload controls</td></tr>\n<tr><td><code>app/console/page.tsx</code></td><td>Admin console</td></tr>\n</tbody></table>\n<p>New tenant? Start with <a href="/docs/technical/entra-id-setup">Entra ID setup</a>, then <a href="/docs/technical/azure-email">Azure email setup</a>, then wire env vars on <a href="/docs/technical/cloudways-deploy">Cloudways deploy</a>. Continue with <a href="/docs/technical/architecture">Architecture</a> or <a href="/docs/technical/api-reference">API reference</a>.</p>';

export default function Page() {
  return (
    <DocArticle title='Technical overview'>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </DocArticle>
  );
}
