import { DocArticle } from "@/components/docsChrome";

const html = '<p>Defaults live in <code>lib/appConfig.ts</code>. Overrides persist in Redis via Settings / <code>PUT /api/config</code>.</p>\n<table>\n<thead><tr><th>Field</th><th>Default</th><th>Role</th></tr></thead>\n<tbody>\n<tr><td><code>folderName</code></td><td><code>uploads</code></td><td>OneDrive destination folder under drive root</td></tr>\n<tr><td><code>bufferTimeMs</code></td><td><code>60000</code> (1 min)</td><td>Delay before a new link becomes usable</td></tr>\n<tr><td><code>linkExpiryTimeMs</code></td><td><code>3600000</code> (1 h)</td><td>Parent upload window; Redis keeps the key one extra day for the console list</td></tr>\n<tr><td><code>fileDetails.maxFileCount</code></td><td><code>1</code></td><td>One video per upload</td></tr>\n<tr><td><code>fileDetails.maxFileSizeBytes</code></td><td>4 GB</td><td>Hard max</td></tr>\n<tr><td><code>fileDetails.maxSimpleFileSizeBytes</code></td><td>4 MB</td><td>Threshold for simple vs session upload</td></tr>\n<tr><td><code>fileDetails.uploadChunkSizeBytes</code></td><td>10 MB</td><td>Resumable chunk size</td></tr>\n<tr><td><code>referenceSheetName</code></td><td><code>REFERENCE.xlsx</code></td><td>Workbook for child picker</td></tr>\n<tr><td><code>childNameColumn</code> / <code>edcColumn</code></td><td><code>Child Name</code> / <code>EDC</code></td><td>Excel headers (or letters)</td></tr>\n<tr><td><code>allowedAdminEmails</code></td><td>defaults + env</td><td>Who may use <code>/console</code> and own the drive</td></tr>\n</tbody></table>\n<p>Accepted upload types default to <code>video/*</code> (client also accepts empty MIME + common video extensions for iOS).</p>\n<h2>Extending safely</h2>\n<table>\n<thead><tr><th>Change</th><th>Suggested approach</th></tr></thead>\n<tbody>\n<tr><td>New setting</td><td>Add to <code>AppConfig</code> + defaults + Settings UI + <code>updateAppConfig</code> merge</td></tr>\n<tr><td>New API</td><td>Place under <code>app/api/…/route.ts</code>; call access helpers explicitly</td></tr>\n<tr><td>Filename scheme</td><td>Adjust <code>lib/uploadFilename.ts</code>; keep age logic in <code>lib/age.ts</code></td></tr>\n<tr><td>Extra notification channel</td><td>Hook beside <code>sendUploadNotificationEmail</code> in <code>/api/upload/complete</code></td></tr>\n<tr><td>UI copy</td><td>Prefer <code>app/page.tsx</code> / console page; keep legal copy via <code>lib/publisher.ts</code></td></tr>\n</tbody></table>';

export default function Page() {
  return (
    <DocArticle title='Configuration'>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </DocArticle>
  );
}
